name: Deploy EKS and Kubernetes resources with Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Provisionar infraestrutura com Terraform
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: â¬ Checkout do cÃ³digo
      uses: actions/checkout@v3

    - name: ğŸ› ï¸ Instalar Kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: ğŸ› ï¸ Instalar Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: ğŸ” Configurar credenciais AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: ğŸ“ Inicializar Terraform
      run: terraform init
    
    - name: ğŸ“ Tenta importar o clues se jÃ¡ existir
      run: terraform import aws_eks_cluster.pedidos pedidos-cluster || echo "Cluster nÃ£o existe, serÃ¡ criado..."

    - name: ğŸ§ª Verificar estado do Terraform
      run: terraform state list
    
    - name: ğŸ”„ Sincronizar estado do Terraform
      run: terraform refresh

    - name: ğŸ§ª Validar Terraform
      run: terraform validate

    - name: ğŸ“‹ Planejar Terraform
      run: terraform plan -out=tfplan

    - name: ğŸš€ Aplicar Terraform
      run: terraform apply -auto-approve tfplan
